export APP_ID=$(ls -an /data/data/ch.gridvision.ppam.androidautomagic/shared_prefs | grep -o "10....10..." | head -n 1 | grep -o "10... ");
echo $APP_ID;
pm grant ch.gridvision.ppam.androidautomagic android.permission.ACCESS_COARSE_LOCATION;
pm grant ch.gridvision.ppam.androidautomagic android.permission.ACCESS_FINE_LOCATION;
pm grant ch.gridvision.ppam.androidautomagic android.permission.CALL_PHONE;
pm grant ch.gridvision.ppam.androidautomagic android.permission.CAMERA;
pm grant ch.gridvision.ppam.androidautomagic android.permission.DUMP;
pm grant ch.gridvision.ppam.androidautomagic android.permission.PROCESS_OUTGOING_CALLS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.READ_CALENDAR;
pm grant ch.gridvision.ppam.androidautomagic android.permission.READ_CONTACTS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.READ_LOGS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.READ_PHONE_STATE;
pm grant ch.gridvision.ppam.androidautomagic android.permission.RECEIVE_SMS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.RECORD_AUDIO;
pm grant ch.gridvision.ppam.androidautomagic android.permission.SEND_SMS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.WRITE_CALENDAR;
pm grant ch.gridvision.ppam.androidautomagic android.permission.WRITE_CONTACTS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.WRITE_EXTERNAL_STORAGE;
pm grant ch.gridvision.ppam.androidautomagic android.permission.SYSTEM_ALERT_WINDOW;
pm grant ch.gridvision.ppam.androidautomagic android.permission.GET_ACCOUNTS;
pm grant ch.gridvision.ppam.androidautomagic com.google.android.gm.permission.READ_CONTENT_PROVIDER;
pm grant ch.gridvision.ppam.androidautomagic android.permission.READ_CALL_LOG;
pm grant ch.gridvision.ppam.androidautomagic android.permission.WRITE_CALL_LOG;
pm grant ch.gridvision.ppam.androidautomagic android.permission.ANSWER_PHONE_CALLS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER;
pm grant ch.gridvision.ppam.androidautomagic android.permission.INTERACT_ACROSS_USERS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.SIGNAL_PERSISTENT_PROCESSES;
pm grant ch.gridvision.ppam.androidautomagic android.permission.CHANGE_CONFIGURATION;
pm grant ch.gridvision.ppam.androidautomagic android.permission.PACKAGE_USAGE_STATS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.WRITE_SECURE_SETTINGS;
pm grant ch.gridvision.ppam.androidautomagic net.dinglisch.android.tasker.PERMISSION_RUN_TASKS;
pm grant ch.gridvision.ppam.androidautomagic android.permission.READ_EXTERNAL_STORAGE;
pm grant ch.gridvision.ppam.androidautomagic android.permission.ACTIVITY_RECOGNITION;
pm grant ch.gridvision.ppam.androidautomagic android.permission.ACCESS_BACKGROUND_LOCATION;
pm grant ch.gridvision.ppam.androidautomagic android.permission.ACCESS_MEDIA_LOCATION;
cp -r /sdcard/Tasker/shared_prefs-ch.gridvision.ppam.androidautomagic_preferences.xml /data/data/ch.gridvision.ppam.androidautomagic/shared_prefs/ch.gridvision.ppam.androidautomagic_preferences.xml;
chown $APP_ID:$APP_ID /data/data/ch.gridvision.ppam.androidautomagic/shared_prefs/*
